# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb6b18c0f3331311ac0ebb75c289a1742bc6697a53fd0109c687a1fb068cb6784f74a9663ee9eabcc3d6a0faae5a7cc590c5f1248d821e77643c2401a7b4e840

test:
  secret_key_base: 1c64f1f570d03a890e1f45a0c4a81cb005591e886a36391a19d8687896b16f29cd1e368f1295637bf169134f2a02888319475e54c09a43fcac4491bd402aff1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
